### ISSUE TITLE
Stop crawl process

### ISSUE THREAD

**Issue by Fred-el-Jolo** [Bhaal22/whatsclose#43]

**Comment by Bhaal22** [comment]
Do not really know how to do it ... since eveything is async I do not find any criteria for termination ...

**Comment by Bhaal22** [comment]
I created a Map :
 BandName -> #concerts

for each bands to index during the current session.
At each geocode_ok or geocode_multiple decrease the corresponding entry in the Map.

Need to manage geocoding errors.
